import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { ThemeProvider } from "@/components/ThemeProvider";
import { ThemeSwitcher } from "@/components/ThemeSwitcher";
import { Comic_Relief, Playfair_Display } from "next/font/google";
import { auth } from "@/auth";
import { headers } from "next/headers";

const comicRelief = Comic_Relief({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-comic-relief",
  adjustFontFallback: false,
});

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair-display",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth.api.getSession({
    headers: await headers(),
  });

  return (
    <html
      lang="en"
      className={`h-full antialiased ${comicRelief.variable} ${playfairDisplay.variable}`}
    >
      <body className="min-h-full bg-background px-4 text-foreground sm:px-6 lg:px-10 xl:px-16">
        <ThemeProvider>
          <nav className="flex flex-wrap items-center justify-between gap-3 bg-background py-4 text-foreground">
            <Link href="/" className="text-xl font-bold sm:text-2xl">
              TostySCI
            </Link>
            <div className="flex flex-wrap items-center justify-end gap-2 sm:gap-3">
              <ThemeSwitcher />
              {session ? (
                <div className="flex flex-wrap items-center justify-end gap-2 sm:gap-4">
                  <Link href="/dashboard/ingredients" className="text-base font-semibold sm:text-lg">Składniki</Link>
                  <span className="inline-flex items-center rounded-lg bg-secondary px-3 py-2 text-sm font-semibold leading-none text-background sm:px-4 sm:py-2.5 sm:text-base">
                    {session.user.name}
                  </span>

                </div>
              ) : (
                <>
                  <Link href="/login" className="inline-flex items-center rounded-lg bg-secondary px-3 py-2 text-sm font-semibold leading-none text-background sm:px-4 sm:py-2.5 sm:text-base">
                    Login
                  </Link>
                  <Link href="/register" className="inline-flex items-center rounded-lg bg-secondary px-3 py-2 text-sm font-semibold leading-none text-background sm:px-4 sm:py-2.5 sm:text-base">
                    Register
                  </Link>
                </>
              )}
            </div>
          </nav>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}