import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { ThemeProvider } from "@/components/ThemeProvider";
import { ThemeSwitcher } from "@/components/ThemeSwitcher";
import { Comic_Relief, Playfair_Display } from "next/font/google";
import { auth } from "@/auth";
import { headers } from "next/headers";

const comicRelief = Comic_Relief({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-comic-relief",
  adjustFontFallback: false,
});

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair-display",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth.api.getSession({
    headers: await headers(),
  });

  return (
    <html
      lang="en"
      className={`h-full antialiased ${comicRelief.variable} ${playfairDisplay.variable}`}
    >
      <body className="min-h-full flex flex-col bg-background text-foreground">
        <ThemeProvider>
          <nav className="bg-background text-foreground px-24 py-4 flex flex-row items-center justify-between">
            <Link href="/" className="text-2xl font-bold">
              TostySCI
            </Link>
            <div className="flex items-center gap-3">
              <ThemeSwitcher />
              {session ? (
                <span className="inline-flex items-center leading-none text-2xl font-semibold bg-secondary text-background px-5 py-3 rounded-lg">
                  {session.user.name}
                </span>
              ) : (
                <>
                  <Link href="/login" className="inline-flex items-center leading-none text-2xl font-semibold bg-secondary text-background px-5 py-3 rounded-lg">
                    Login
                  </Link>
                  <Link href="/register" className="inline-flex items-center leading-none text-2xl font-semibold bg-secondary text-background px-5 py-3 rounded-lg">
                    Register
                  </Link>
                </>
              )}
            </div>
          </nav>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}